/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInferface;

import MainModel.StudentClass;
import javax.swing.JPanel;

/**
 *
 * @author dipenpatel
 */
public class ViewaddcourseStudentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewaddcourseStudentJPanel
     */
//    public ViewaddcourseStudentJPanel() {
//        initComponents();
//    }
    private StudentClass StudentClass;
    private JPanel WorkArea;
    ViewaddcourseStudentJPanel(JPanel WorkArea,StudentClass StudentClass) {
        initComponents();
        this.WorkArea=WorkArea;
        this.StudentClass=StudentClass;
        popluateTable();
        System.out.println("See here");
        System.out.println(StudentClass.getAddcourses()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTerm = new javax.swing.JTextField();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(txtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(txtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtTerm;
    // End of variables declaration//GEN-END:variables

    private void popluateTable() {
        txtTerm.setText(StudentClass.getAddcourses().get(1));
    }
}
